export function crearFichaBase(nombre = '') {
    return {
        nombre,
        nivel: 1,
        version: 1.0,
        pokedex: {
            especie: '',
            tipos: ['', ''],
            statsBase: { fue: 0, agi: 0, res: 0, men: 0, esp: 0, pre: 0 },
            salvaciones: { fue: 0, agi: 0, res: 0, esp: 0 },
            natHabil: [],
            vit: 0,
            velocidades: { Caminado: 0, Trepado: 0, Excavado: 0, Nado: 0, Vuelo: 0, Levitado: 0 },
            movimientosNivel: [],
            movimientosEnseñables: [],
            habilidades: [],
            habilidadesOcultas: [],
            calculosEva: [],
            otros: { dieta: '', tamano: '', sexo: '', sentidos: '', evolucion: '' },
        },
        personaliz: {
            mejorasEst: [],
            movimientosAprendidos: [],
            movimientosExtra: [],
            habilidadesOcultasDesbloqueadas: [],
            habOpcionalElegida: null,
            habilidadesExtra: [],
            dotes: [],
            dotesExtra: [],
            mejorasHab: [],
            evaDisponibles: [],
            salvaciones: { fue: 0, agi: 0, res: 0, esp: 0 },
            teratipo: '',
            sentidos: '',
            naturaleza: { naturaleza: '', check: '' },
            amuleto: ''
        },
        derivados: {
            bh: 0,
            stats: { fue: 0, agi: 0, res: 0, men: 0, esp: 0, pre: 0 },
            salvaciones: { fue: 0, agi: 0, res: 0, esp: 0 },
            velocidades: { Caminado: 0, Trepado: 0, Excavado: 0, Nado: 0, Vuelo: 0, Levitado: 0 },
            cantidadMejorasEST: 0,
            cantidadMejorasHab: 0,
            cantidadDotes: 0,
            cantidadMovs: 0,
            evaElegida: 0,
            evasiones: [0],
            evasion: 0,
            pp: 0,
            ppMax: 0,
            pv: 0,
            pvMax: 0,
            escudo: 0,
            fatiga: 0,
            carga: 0,
            vit: 0,
            sentidos: ''
        },
        checks: {
            checksBase: [{ check: 'Percepción', grado: 1 }, { check: 'Init', grado: 1 }],
            checksData: []
        },
        modificadores: {
            pvMax: 0,
            ppMax: 0,
            vit: 0,
            bh: 0,
            evasion: 0,
            mejorasHab: 0,
            stats: { fue: 0, agi: 0, res: 0, men: 0, esp: 0, pre: 0 },
            velocidades: { Caminado: 0, Trepado: 0, Excavado: 0, Nado: 0, Vuelo: 0, Levitado: 0 }
        }
    }
}
