// Archivo: fichaBase.js
export function crearFichaBase(nombre = '') {
    return {
        nombre,
        nivel: 1,
        pokedex: {
            especie: '',
            tipos: ['', ''],
            statsBase: { fue: 0, agi: 0, res: 0, men: 0, esp: 0, pre: 0 },
            salvaciones: { fue: 0, agi: 0, res: 0, esp: 0 },
            natHabil: '',
            vit: 0,
            velocidades: { Caminado: 0, Trepado: 0, Excavado: 0, Nado: 0, Vuelo: 0, Levitado: 0 },
            movimientosDisponibles: [],
            Habilidades: [],
            HabilidadesOcultas: [],
            calculosCA: ['', ''],
            Evolución: [],
            otros: { dieta: '', tamano: '', sexo: '', sentidos: '' },
        },
        personaliz: {
            mejorasEst: [],
            movimientosAprendidos: [],
            habilidadesDisponibles: [],
            dotes: [],
            checksActivos: [],
            checksBonos: [],
            checksNuevos: ['TDA personalizadas'],
            mejorasHab: ['TDA', 'Numero de mejoras'],
            caDisponibles: ['', ''],
            bonosExtraEst: { fue: 0, agi: 0, res: 0, men: 0, esp: 0, pre: 0 },
            mejorasVelocidades: { Caminado: 0, Trepado: 0, Excavado: 0, Nado: 0, Vuelo: 0, Levitado: 0 },
            salvaciones: { fue: 0, agi: 0, res: 0, esp: 0 },
            bonoVit: 0,
            bonoPP: 0,
            bonoInit: 0,
            bonoCa: 0,
            teratipo: '',
            sentidos: ''
        },
        derivados: {
            bh: 0,
            stats: { fue: 0, agi: 0, res: 0, men: 0, esp: 0, pre: 0 },
            salvaciones: { fue: 0, agi: 0, res: 0, esp: 0 },
            checks: [{ check: 'nombreCheck', bono: 'bono' }],
            velocidades: { Caminado: 0, Trepado: 0, Excavado: 0, Nado: 0, Vuelo: 0, Levitado: 0 },
            cantidadMejorasEST: 0,
            init: 0,
            ca: 0,
            pp: 0,
            ppMax: 0,
            pv: 0,
            pvMax: 0,
            escudo: 0,
            fatiga: 0,
            carga: 0,
            vit: 0,
        },
        manual: {
            bh: false,
            ppMax: false,
            cantidadMejorasEST: false
        },
    }
}
