export function crearFichaBase(nombre = '') {
    return {
        nombre,
        nivel: 1,
        pokedex: {
            especie: '',
            tipos: ['', ''],
            statsBase: { fue: 0, agi: 0, res: 0, men: 0, esp: 0, pre: 0 },
            salvaciones: { fue: 0, agi: 0, res: 0, esp: 0 },
            natHabil: [],
            vit: 0,
            velocidades: { Caminado: 0, Trepado: 0, Excavado: 0, Nado: 0, Vuelo: 0, Levitado: 0 },
            movimientosNivel: [],
            movimientosEnseñables: [],
            habilidades: [],
            habilidadesOcultas: [],
            calculosCA: [],
            otros: { dieta: '', tamano: '', sexo: '', sentidos: '', evolucion: '' },
        },
        personaliz: {
            mejorasEst: [],
            movimientosAprendidos: [],
            movimientosExtra: [],
            habilidadesOcultasDesbloqueadas: [],
            habOpcionalElegida: null,
            habilidadesExtra: [],
            dotes: [],
            dotesExtra: [],
            checks: [],
            mejorasHab: [],
            caDisponibles: [],
            bonosExtraEst: { fue: 0, agi: 0, res: 0, men: 0, esp: 0, pre: 0 },
            mejorasVelocidades: { Caminado: 0, Trepado: 0, Excavado: 0, Nado: 0, Vuelo: 0, Levitado: 0 },
            salvaciones: { fue: 0, agi: 0, res: 0, esp: 0 },
            bonoVit: 0,
            bonoPP: 0,
            bonoCa: 0,
            teratipo: '',
            sentidos: '',
            naturaleza: { naturaleza: '', check: '' },
            amuleto: ''
        },
        derivados: {
            bh: 0,
            stats: { fue: 0, agi: 0, res: 0, men: 0, esp: 0, pre: 0 },
            salvaciones: { fue: 0, agi: 0, res: 0, esp: 0 },
            checksBase: [{ check: 'Percepción', grado: 'bueno' }],
            velocidades: { Caminado: 0, Trepado: 0, Excavado: 0, Nado: 0, Vuelo: 0, Levitado: 0 },
            cantidadMejorasEST: 0,
            cantidadMejorasHab: 0,
            cantidadDotes: 0,
            cantidadMovs: 0,
            init: 0,
            caElegida: 0,
            cas: [0],
            ca: 0,
            pp: 0,
            ppMax: 0,
            pv: 0,
            pvMax: 0,
            escudo: 0,
            fatiga: 0,
            carga: 0,
            vit: 0,
            sentidos: ''
        },
        manual: {
            bh: false,
            ppMax: false,
            pvMax: false,
            vit: false,
            init: false,
            ca: false,
            tiradasHab: false,
            cantidadMejorasEST: false,
            cantidadMejorasHab: false
        },
    }
}
